apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: sabinolabs
      context: ../spring-boot-microservices-kotlin
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
